Update jaxb implementation
OpenLiberty/liberty-language-server pull request #158
Opened 2023-01-19 22:33 UTC by evie-lau

Fixes #142

2023-01-19 22:44 UTC, cherylking requested changes
I'm glad the fix is straight forward! Two things though:

1) Update copyrights to include 2023.
2) Can a test be updated for this to prove it works?

2023-01-19 22:57 UTC, scottkurz commented
@evie-lau just curious...how was this tested so far?

2023-01-19 23:05 UTC, evie-lau commented
> @evie-lau just curious...how was this tested so far?

I only tested manually, by building the jar and running the VSCode plugin. 
I haven't looked into the existing tests yet, but I can take a look to see if we can add a test for this. Would it be specifically for testing the open liberty beta runtime?

2023-01-20 01:20 UTC, cherylking requested changes
Fix copyright format for each file. Also, the test would have to be with the beta runtime to force this code path. Unless you invent some unit test and check in a mock feature list xml file and make sure it loads correctly using the jaxb code?

2023-01-20 01:20 UTC, cherylking commented on lemminx-liberty/src/main/java/io/openliberty/tools/langserver/lemminx/models/feature/Feature.java
> +* Copyright (c) 2020-2023 IBM Corporation and others.
Not sure why you used a different format here? It should be `2020, 2022`

2023-01-20 21:00 UTC, evie-lau commented
Working on a unit test for using the beta runtime. Looking like I'll have to check in a `ws-featurelist.jar`.

2023-01-20 22:49 UTC, scottkurz requested changes
Looks good.  I tested it in Eclipse and it works.  I sent a PR to update the NOTICES coordinates https://github.com/evie-lau/liberty-language-server/pull/1

As far as testing.. I was just curious.   I'm not suggesting it's a MUST to merge this.

2023-01-20 22:59 UTC, cherylking approved these changes

2023-01-20 23:03 UTC, scottkurz approved these changes

2023-01-20 23:10 UTC, merged