fix for bootstrap properties code completion replacing existing line
OpenLiberty/liberty-language-server pull request #306
Opened 2024-10-07 13:32 UTC by arunvenmany-ibm

2024-10-07 13:33 UTC, arunvenmany-ibm commented
https://github.com/user-attachments/assets/76384561-4461-4a24-b5a6-59508ac789cd

2024-10-07 19:59 UTC, cherylking requested changes
The change looks good. Just one question...why did I see a diagnostic flagged when you selected the bootstrap property `com.ibm.ws.logging.console.source` in the video (at 18 seconds)?

2024-10-07 19:59 UTC, cherylking commented on liberty-ls/src/main/java/io/openliberty/tools/langserver/model/propertiesfile/PropertiesKeyInstance.java
> +import org.eclipse.lsp4j.InsertReplaceEdit;
Update copyright to include 2024.

2024-10-08 04:26 UTC, arunvenmany-ibm commented
> The change looks good. Just one question...why did I see a diagnostic flagged when you selected the bootstrap property `com.ibm.ws.logging.console.source` in the video (at 18 seconds)?

Thats because we have not set the property value. once set value for the property, diagnostic disappeared

<img width="540" alt="image" src="https://github.com/user-attachments/assets/6d86f164-a04d-4e8c-828f-bdf520121107">
<img width="800" alt="image" src="https://github.com/user-attachments/assets/05f2c021-098c-40b9-9498-75a52b12a48b">

Once some value is set, diagnostic is disappeared
<img width="449" alt="image" src="https://github.com/user-attachments/assets/993dda10-0bc9-4d12-ae6a-0b725b729455">

2024-10-08 04:28 UTC, arunvenmany-ibm commented on liberty-ls/src/main/java/io/openliberty/tools/langserver/model/propertiesfile/PropertiesKeyInstance.java
> +import org.eclipse.lsp4j.InsertReplaceEdit;
Done

2024-10-08 12:01 UTC, cherylking approved these changes

2024-10-08 12:08 UTC, merged