Add value completion for properties
OpenLiberty/liberty-language-server pull request #74
Opened 2022-06-24 18:46 UTC by evie-lau

Add value completion for properties in server.env and bootstrap.properties files
The `ServerPropertyValues` class contains the HashMaps for properties to valid values, and utilizes the `EquivalentProperties` for bootstrap properties to grab the same values as server.env properties.

2022-06-24 18:57 UTC, evie-lau commented
Question: for properties that can define directory paths such as these, should we have the autocomplete suggest the default value?
```
wlp.user.dir=The directory of the usr folder. The default is `${wlp.install.dir}/usr`.
shared.app.dir=The directory of shared applications. The default is `${wlp.user.dir}/shared/apps`.
shared.config.dir=The directory of shared configuration files. The default is `${wlp.user.dir}/shared/config`.
shared.resource.dir=The directory of shared resource files. The default is `${wlp.user.dir}/shared/resources`.
```

2022-06-28 16:38 UTC, cherylking commented
> Question: for properties that can define directory paths such as these, should we have the autocomplete suggest the default value?
> 
> ```
> wlp.user.dir=The directory of the usr folder. The default is `${wlp.install.dir}/usr`.
> shared.app.dir=The directory of shared applications. The default is `${wlp.user.dir}/shared/apps`.
> shared.config.dir=The directory of shared configuration files. The default is `${wlp.user.dir}/shared/config`.
> shared.resource.dir=The directory of shared resource files. The default is `${wlp.user.dir}/shared/resources`.
> ```

I think you should ask this in the devex guild slack channel.

2022-06-28 19:20 UTC, cherylking commented on liberty-ls/src/main/java/io/openliberty/tools/langserver/utils/ServerPropertyValues.java
> +package io.openliberty.tools.langserver.utils;
Add copyright.

2022-06-28 19:24 UTC, cherylking commented on liberty-ls/src/main/resources/ServerEnv.properties
> -WLP_OUTPUT_DIR=The directory that contains output files for defined servers. This directory must have both read and write permissions for the user or users who start servers. By default, the server o
Why are these being removed?

2022-06-28 19:26 UTC, cherylking commented on liberty-ls/src/main/java/io/openliberty/tools/langserver/utils/ServerPropertyValues.java
> +public class ServerPropertyValues {
What about properties that have a certain data type, like it should be an integer? Is there anything we will do to flag incorrect values for those?

2022-06-28 19:30 UTC, evie-lau commented on liberty-ls/src/main/resources/ServerEnv.properties
> -WLP_OUTPUT_DIR=The directory that contains output files for defined servers. This directory must have both read and write permissions for the user or users who start servers. By default, the server o
These are duplicate entries

2022-06-28 20:03 UTC, cherylking commented on liberty-ls/src/main/java/io/openliberty/tools/langserver/utils/ServerPropertyValues.java
> +public class ServerPropertyValues {
Ok, if we don't have an issue open for validating values, please go ahead and open one.

2022-06-28 21:16 UTC, evie-lau commented on liberty-ls/src/main/java/io/openliberty/tools/langserver/model/propertiesfile/PropertiesEntryInstance.java
> +        if (propertyValueInstance.toString() != null) {
Added the position check

2022-06-29 19:13 UTC, cherylking requested changes

2022-06-29 19:13 UTC, cherylking commented on liberty-ls/src/main/java/io/openliberty/tools/langserver/utils/Messages.java
> +            LOGGER.fine("Can't find property description for: " + key);
Suggested rewording: "No property description found for: "

2022-06-29 20:24 UTC, merged